language: sh

services:
  - docker

before_install:
  - cd bitcoin-core
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t cyphernode/bitcoin:x86_64-0.21.0 --build-arg ARCH=x86_64 .
  - docker run -d -p 8333:8333 cyphernode/bitcoin:x86_64-0.21.0 /bin/sh -c "bitcoind -regtest -deamon"
  - docker ps -a

script:
  - docker run -rm /bin/sh -c bitcoin-cli -regtest generatetoaddress 101 $(bitcoin-cli -regtest getnewaddress)


