language: sh

services:
  - docker

before_install:
  - cd bitcoin-core
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t cyphernode/bitcoin:x86_64-0.21.0 --build-arg ARCH=x86_64 .
  - docker run -d -p 8333:8333 cyphernode/bitcoin:x86_64-0.21.0 /bin/sh -c "bitcoind -regtest -deamon"
  - docker ps -a

script:
  - docker exec -it $(docker ps -q -f "health=healthy") bitcoin-cli getpeerinfo
  
  #-regtest generatetoaddress 101 $(bitcoin-cli -regtest getnewaddress)

